In [1]:
import pandas as pd

In [2]:
data = pd.read_parquet('data/data.parquet', engine='pyarrow')

In [3]:
data[['Text_EN', 'Text_PL', 'Text_RU', 'Translation_quality']][data['Translation_quality'] == 0.0]

,Text_EN,Text_PL,Text_RU,Translation_quality
4,"<user> <user> <user> Just take the L g, or fin...",<user> <user> <user> Po prostu we≈∫ L g lub zna...,"<user> <user> <user> –ü—Ä–æ—Å—Ç–æ –≤–æ–∑—å–º–∏ L g, –∏–ª–∏ –Ω–∞...",0.0
86,<user> <user> Deez Nuts,<user> <user> Deez Nuts,<user> <user> Deez Nuts,0.0
265,<user> <user> AIMS???!ü•¥,<user> <user> AIMS??!ü•¥,<user> <user> AIMS???!ü•¥,0.0

In [2]:
data = pd.read_csv('data/MD-Agreement_dataset.tsv', sep='\t')

In [3]:
data

,ID,Text,Agreement_level,Offensive_binary_label,Individual_Annotations,Annotators_ID,Domain
0,1_train,<user> <user> No way Jose!!,A++,0,"0,0,0,0,0","Ann418,Ann266,Ann149,Ann730,Ann345",Elections2020
1,2_train,"Good god, what is the matter with people ?",A++,0,"0,0,0,0,0","Ann733,Ann422,Ann779,Ann514,Ann777",Covid-19
2,3_train,<user> <user> <user> <user> Um the Kurds are h...,A+,0,"0,0,0,0,1","Ann425,Ann511,Ann779,Ann420,Ann721",Elections2020
3,4_train,What is WRONG with these people?,A++,0,"0,0,0,0,0","Ann632,Ann179,Ann701,Ann201,Ann661",BLM
4,5_train,<user> This earpiece too plus a wire on his sl...,A+,0,"1,0,0,0,0","Ann266,Ann168,Ann149,Ann381,Ann774",Elections2020
...,...,...,...,...,...,...,...
9809,3053_test,<user> you‚Äôre a bold faced liar. You will be u...,A0,1,"0,0,1,1,1","Ann676,Ann492,Ann683,Ann71,Ann571",Elections2020
9810,3054_test,<user> <user> <user> hey NJ even <user> can vo...,A0,0,"0,0,0,1,1","Ann64,Ann21,Ann688,Ann229,Ann538",Elections2020
9811,3055_test,And people ask me and my peers why we hate our...,A0,0,"0,1,0,1,0","Ann535,Ann368,Ann329,Ann229,Ann408",BLM
9812,3056_test,<user> if you love us BLACK People so much th...,A+,0,"0,1,0,0,0","Ann329,Ann229,Ann535,Ann546,Ann602",BLM
9813,3057_test,We are not playing! #BlackLivesMatter,A++,0,"0,0,0,0,0","Ann462,Ann535,Ann85,Ann45,Ann21",BLM

In [7]:
ann_ids = list()
for i in range(len(data)):
    annids = data.iloc[i, 5]
    for annid in annids.split(','):
        ann_ids.append(annid)

In [9]:
len(set(ann_ids))

819

In [10]:
data[data['Domain'] == "Elections2020"]

,ID,Text,Agreement_level,Offensive_binary_label,Individual_Annotations,Annotators_ID,Domain
0,1_train,<user> <user> No way Jose!!,A++,0,"0,0,0,0,0","Ann418,Ann266,Ann149,Ann730,Ann345",Elections2020
2,3_train,<user> <user> <user> <user> Um the Kurds are h...,A+,0,"0,0,0,0,1","Ann425,Ann511,Ann779,Ann420,Ann721",Elections2020
4,5_train,<user> This earpiece too plus a wire on his sl...,A+,0,"1,0,0,0,0","Ann266,Ann168,Ann149,Ann381,Ann774",Elections2020
5,6_train,<user> <user> Please lost you yelling insanely...,A0,1,"1,0,1,0,1","Ann517,Ann401,Ann149,Ann212,Ann779",Elections2020
7,8_train,"<user> <user> <user> Just take the L g, or fin...",A++,0,"0,0,0,0,0","Ann334,Ann811,Ann573,Ann569,Ann779",Elections2020
...,...,...,...,...,...,...,...
9803,3047_test,<user> <user> <user> Imagine being this dumb.,A0,1,"1,0,0,1,1","Ann492,Ann683,Ann206,Ann71,Ann571",Elections2020
9804,3048_test,Is it still called democracy when your only op...,A0,1,"0,1,1,1,0","Ann638,Ann85,Ann789,Ann283,Ann728",Elections2020
9808,3052_test,<user> YES! I support your decision to never ...,A0,1,"0,0,1,1,1","Ann283,Ann734,Ann416,Ann789,Ann494",Elections2020
9809,3053_test,<user> you‚Äôre a bold faced liar. You will be u...,A0,1,"0,0,1,1,1","Ann676,Ann492,Ann683,Ann71,Ann571",Elections2020
9810,3054_test,<user> <user> <user> hey NJ even <user> can vo...,A0,0,"0,0,0,1,1","Ann64,Ann21,Ann688,Ann229,Ann538",Elections2020